export enum InputType {
  Text = "text",
  Password = "password",
  Email = "email",
  Number = "number",
  Date = "date",
  Checkbox = "checkbox",
  Radio = "radio",
  Submit = "submit",
  Reset = "reset",
  Button = "button",
  Color = "color",
  File = "file",
  Image = "image",
  Range = "range",
  Search = "search",
  Tel = "tel",
  Url = "url",
}
